[2024-01-18T22:01:50.112+0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Google_X_mention_score.test_model_naive scheduled__2024-01-01T01:30:00+00:00 [queued]>
[2024-01-18T22:01:50.127+0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Google_X_mention_score.test_model_naive scheduled__2024-01-01T01:30:00+00:00 [queued]>
[2024-01-18T22:01:50.128+0300] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-01-18T22:01:50.128+0300] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2024-01-18T22:01:50.128+0300] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-01-18T22:01:50.153+0300] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): test_model_naive> on 2024-01-01 01:30:00+00:00
[2024-01-18T22:01:50.162+0300] {standard_task_runner.py:55} INFO - Started process 5577 to run task
[2024-01-18T22:01:50.171+0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'Google_X_mention_score', 'test_model_naive', 'scheduled__2024-01-01T01:30:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/google_mention_score.py', '--cfg-path', '/tmp/tmpget_23z0']
[2024-01-18T22:01:50.175+0300] {standard_task_runner.py:83} INFO - Job 22: Subtask test_model_naive
[2024-01-18T22:01:50.286+0300] {task_command.py:389} INFO - Running <TaskInstance: Google_X_mention_score.test_model_naive scheduled__2024-01-01T01:30:00+00:00 [running]> on host xflow
[2024-01-18T22:01:50.377+0300] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=Google_X_mention_score
AIRFLOW_CTX_TASK_ID=test_model_naive
AIRFLOW_CTX_EXECUTION_DATE=2024-01-01T01:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-01T01:30:00+00:00
[2024-01-18T22:01:50.380+0300] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-01-18T22:01:50.382+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/angry/mlops_4/scripts/test_model.py naive']
[2024-01-18T22:01:50.405+0300] {subprocess.py:86} INFO - Output:
[2024-01-18T22:01:55.509+0300] {subprocess.py:97} INFO - Command exited with return code 0
[2024-01-18T22:01:55.545+0300] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=Google_X_mention_score, task_id=test_model_naive, execution_date=20240101T013000, start_date=20240118T190150, end_date=20240118T190155
[2024-01-18T22:01:55.608+0300] {local_task_job.py:212} INFO - Task exited with return code 0
[2024-01-18T22:01:55.625+0300] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
