[2024-01-18T21:59:12.682+0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Google_X_mention_score.process_data manual__2024-01-18T18:56:27.556327+00:00 [queued]>
[2024-01-18T21:59:12.703+0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Google_X_mention_score.process_data manual__2024-01-18T18:56:27.556327+00:00 [queued]>
[2024-01-18T21:59:12.704+0300] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-01-18T21:59:12.705+0300] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2024-01-18T21:59:12.705+0300] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-01-18T21:59:12.736+0300] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): process_data> on 2024-01-18 18:56:27.556327+00:00
[2024-01-18T21:59:12.747+0300] {standard_task_runner.py:55} INFO - Started process 5429 to run task
[2024-01-18T21:59:12.766+0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'Google_X_mention_score', 'process_data', 'manual__2024-01-18T18:56:27.556327+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/google_mention_score.py', '--cfg-path', '/tmp/tmp2w2iw1k6']
[2024-01-18T21:59:12.771+0300] {standard_task_runner.py:83} INFO - Job 16: Subtask process_data
[2024-01-18T21:59:12.932+0300] {task_command.py:389} INFO - Running <TaskInstance: Google_X_mention_score.process_data manual__2024-01-18T18:56:27.556327+00:00 [running]> on host xflow
[2024-01-18T21:59:13.076+0300] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=Google_X_mention_score
AIRFLOW_CTX_TASK_ID=process_data
AIRFLOW_CTX_EXECUTION_DATE=2024-01-18T18:56:27.556327+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-18T18:56:27.556327+00:00
[2024-01-18T21:59:13.080+0300] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-01-18T21:59:13.082+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/angry/mlops_4/scripts/process_data.py']
[2024-01-18T21:59:13.107+0300] {subprocess.py:86} INFO - Output:
[2024-01-18T21:59:14.735+0300] {subprocess.py:97} INFO - Command exited with return code 0
[2024-01-18T21:59:14.793+0300] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=Google_X_mention_score, task_id=process_data, execution_date=20240118T185627, start_date=20240118T185912, end_date=20240118T185914
[2024-01-18T21:59:14.847+0300] {local_task_job.py:212} INFO - Task exited with return code 0
[2024-01-18T21:59:14.901+0300] {taskinstance.py:2596} INFO - 1 downstream tasks scheduled from follow-on schedule check
