[2024-01-18T21:57:42.444+0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Google_X_mention_score.train_model_naive manual__2024-01-18T18:56:27.556327+00:00 [queued]>
[2024-01-18T21:57:42.464+0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Google_X_mention_score.train_model_naive manual__2024-01-18T18:56:27.556327+00:00 [queued]>
[2024-01-18T21:57:42.465+0300] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-01-18T21:57:42.465+0300] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2024-01-18T21:57:42.467+0300] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-01-18T21:57:42.501+0300] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): train_model_naive> on 2024-01-18 18:56:27.556327+00:00
[2024-01-18T21:57:42.512+0300] {standard_task_runner.py:55} INFO - Started process 5337 to run task
[2024-01-18T21:57:42.530+0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'Google_X_mention_score', 'train_model_naive', 'manual__2024-01-18T18:56:27.556327+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/google_mention_score.py', '--cfg-path', '/tmp/tmpocz14yue']
[2024-01-18T21:57:42.541+0300] {standard_task_runner.py:83} INFO - Job 12: Subtask train_model_naive
[2024-01-18T21:57:42.673+0300] {task_command.py:389} INFO - Running <TaskInstance: Google_X_mention_score.train_model_naive manual__2024-01-18T18:56:27.556327+00:00 [running]> on host xflow
[2024-01-18T21:57:42.820+0300] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=Google_X_mention_score
AIRFLOW_CTX_TASK_ID=train_model_naive
AIRFLOW_CTX_EXECUTION_DATE=2024-01-18T18:56:27.556327+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-18T18:56:27.556327+00:00
[2024-01-18T21:57:42.829+0300] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-01-18T21:57:42.831+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/angry/mlops_4/scripts/train_model.py naive']
[2024-01-18T21:57:42.868+0300] {subprocess.py:86} INFO - Output:
[2024-01-18T21:57:58.901+0300] {subprocess.py:93} INFO - Registered model 'naive_model' already exists. Creating a new version of this model...
[2024-01-18T21:57:58.966+0300] {subprocess.py:93} INFO - Created version '3' of model 'naive_model'.
[2024-01-18T21:58:00.418+0300] {subprocess.py:97} INFO - Command exited with return code 0
[2024-01-18T21:58:00.484+0300] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=Google_X_mention_score, task_id=train_model_naive, execution_date=20240118T185627, start_date=20240118T185742, end_date=20240118T185800
[2024-01-18T21:58:00.561+0300] {local_task_job.py:212} INFO - Task exited with return code 0
[2024-01-18T21:58:00.637+0300] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
